"""Add packages, payments, and subscriptions

Revision ID: 4c120843d17d
Revises: 1c07cdda9e30
Create Date: 2026-09-02 07:43:20.634709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c120843d17d'
down_revision: Union[str, None] = '1c07cdda9e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###