"""Update server defaults and relationships on payment models

Revision ID: 8a123031d692
Revises: caabf423f7c0
Create Date: 2026-09-02 08:30:39.440146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a123031d692'
down_revision: Union[str, None] = 'caabf423f7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt_question_snapshots', 'question_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.create_foreign_key(None, 'attempt_question_snapshots', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempt_question_snapshots', type_='foreignkey')
    op.alter_column('attempt_question_snapshots', 'question_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###